{"orig": ["https://rest.com.au/insurance/"], "new": "https://rest.com.au/insurance"}
{"orig": ["https://rest.com.au/retirement/retirement-with-rest/how-to-join/"], "new": "https://rest.com.au/retirement/retirement-with-rest/how-to-join"}
{"orig": ["https://rest.com.au/privacy-policy"], "new": "https://rest.com.au/why-rest/about-rest/fund-details/privacy-policy"}
{"orig": ["https://rest.com.au/terms-and-conditions"], "new": "https://rest.com.au/why-rest/about-rest/fund-details/terms-and-conditions"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/Will-your-super-help-you-live-the-life-you-love"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/will-your-super-help-you-live-the-life-you-love"}
{"orig": ["https://rest.com.au/employer/education-for-employees/workplace-seminar", "https://rest.com.au/employer/Work-Place-Seminar"], "new": "https://rest.com.au/employer/work-place-education-sessions"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-I-make-the-most-of-my-super-in-my-40s"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-i-make-the-most-of-my-super-in-my-40s"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-I-make-the-most-of-my-super-in-my-20s"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-i-make-the-most-of-my-super-in-my-20s"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-I-make-the-most-of-my-super-in-my-50s"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-i-make-the-most-of-my-super-in-my-50s"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/can-I-help-my-partner-increase-their-super"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/can-i-help-my-partner-increase-their-super"}
{"orig": ["https://rest.com.au/contact-us?findmymembernumber"], "new": "https://rest.com.au/why-rest/about-rest/contact-us?findmymembernumber"}
{"orig": ["https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-I-make-the-most-of-my-super-in-my-30s"], "new": "https://rest.com.au/tools-advice/learning-centre/super-tips/how-do-i-make-the-most-of-my-super-in-my-30s"}
{"orig": ["https://rest.com.au/member/investments/investments-how-we-invest/bonds"], "new": "https://rest.com.au/investments/how-we-invest/bonds"}
{"orig": ["https://rest.com.au/member/investments/investments-how-we-invest/rest-property-investments"], "new": "https://rest.com.au/investments/how-we-invest/property-investments"}
{"orig": ["https://rest.com.au/member/investments/investments-how-we-invest/rest-investments-in-australian-shares"], "new": "https://rest.com.au/investments/how-we-invest/australian-shares"}
{"orig": ["https://rest.com.au/member/investments/investments-how-we-invest/rest-investments-in-overseas-shares"], "new": "https://rest.com.au/investments/how-we-invest/overseas-shares"}
{"orig": ["https://rest.com.au/Investments/how-we-invest"], "new": "https://rest.com.au/investments/how-we-invest"}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/PDS/RES0495_Investing_Made_Simple_Guide_FA_WEBSAFE.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/pds/investing-made-simple-guide.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Factsheets-and-Brochures/Member/Bonds-FactSheet.PDF"], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/factsheets/bonds-factsheet.pdf"}
{"orig": ["https://rest.com.au/member/investments/compare-ttr?ids=1,15", "https://rest.com.au/ErrorHandling/500.html?aspxerrorpath=/CMSPages/PortalTemplate.aspx"], "new": "https://rest.com.au/errorhandling/500.html?aspxerrorpath=/CMSPages/PortalTemplate.aspx"}
{"orig": ["https://rest.com.au/super/understanding-super/Women-and-super"], "new": "https://rest.com.au/super/understanding-super/women-and-super"}
{"orig": ["https://rest.com.au/NEW-Document-library/Factsheets-and-Brochures/Member/Accessing_your_super_early_FactSheet.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/factsheets/accessing-your-super-early-factsheet.pdf"}
{"orig": ["https://www.rest.com.au/NEW-Document-library/Guides/Member/RES0509_Additional-info-fees-and-costs.pdf?ext=."], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/pds/additional-info-fees-and-costs.pdf?ext=."}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/Member/RES0254_REST_Super-Insurance-Guide-FA_WEBSAFE.pdf?ext=."], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/factsheets/rest-super-insurance-guide-pdf.pdf?ext=."}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/PDS/RES0435_CorporateInsuranceGuide_PDS.pdf?ext=."], "new": "https://cdn.rest.com.au/rest_web/media/documents/insurance/resources/pds/corporate-insurance-guide-pds.pdf?ext=."}
{"orig": ["https://rest.com.au/android"], "new": "https://play.google.com/store/apps/details?id=rest.com.rest&hl=en"}
{"orig": ["https://rest.com.au/apple"], "new": "https://apps.apple.com/au/app/rest-super/id1159541365"}
{"orig": ["https://rest.com.au/why-rest/about-rest/news/Federal-Budget-2017-18"], "new": "https://rest.com.au/why-rest/about-rest/news/federal-budget-2017-18"}
{"orig": ["https://rest.com.au/Document-Library/Publications/Annual-Report/annual-report-2019.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/why-rest/about-rest/corporate-governance/financial-statements/annual-report-2019.pdf"}
{"orig": ["https://rest.com.au/why-rest/about-rest/news/Investment-update-March-2019-quarter"], "new": "https://rest.com.au/why-rest/about-rest/news/investment-update-march-2019-quarter"}
{"orig": ["https://rest.com.au/member/advice?ga-shc=true"], "new": "https://rest.com.au/tools-advice/advice?ga-shc=true"}
{"orig": ["https://rest.com.au/NEW-Document-library/Factsheets-and-Brochures/Member/retirement-income-review.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/forms/retirement-income-review.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/PDS/sen-faq.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/pds/sen-faq.pdf"}
{"orig": ["https://rest.com.au/generate"], "new": "https://generate.rest.com.au/"}
{"orig": ["https://rest.com.au/NEW-Document-library/Corporate-Governance/Annual-Reports/2014/REST-Financial-Statements-2014.pdf"], "new": "https://cdn.rest.com.au/rest_web/media/documents/why-rest/about-rest/corporate-governance/financial-statements/rest-financial-statements-2014.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Employer-enews/early-release-of-super-faqs.pdf"], "new": "https://rest.com.au/new-document-library/employer-enews/early-release-of-super-faqs.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Employer-enews/heads-up.pdf"], "new": "https://rest.com.au/new-document-library/employer-enews/heads-up.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Employer-enews/redundancy-factsheet.pdf"], "new": "https://rest.com.au/new-document-library/employer-enews/redundancy-factsheet.pdf"}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/PDS/RES0495_Investing_Made_Simple_Guide_FA_WEBSAFE.pdf?ext=."], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/pds/investing-made-simple-guide.pdf?ext=."}
{"orig": ["https://rest.com.au/NEW-Document-library/Guides/PDS/RES0495_Pension_PDS_FA_WEBSAFE.pdf?ext=."], "new": "https://cdn.rest.com.au/rest_web/media/documents/tools-advice/resources/pds/pension-pds.pdf?ext=."}
{"orig": ["https://rest.com.au/rest_web/media/documents/employer/superannuation-standard-choice-form.pdf"], "new": "https://rest.com.au/rest_web/media/documents/tools-advice/resources/forms/fund-nomination-form-online.pdf"}
{"orig": ["https://rest.com.au/Investments/Managing-your-investments"], "new": "https://rest.com.au/investments/managing-your-investments"}
