name: Spider

on:
  schedule:
    - cron: "*/45 10 * * *"
  workflow_dispatch:


jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run a single-line script
        run: |
          pip install scrapy

      - name: Delete old file scrapy_output.txt
        run: |
          rm -f /tmp/scrapy_output.txt

      - name: Delete old file rest2.html
        run: |
          rm -f /tmp/rest2.html

      - name: Run a scrapy crawl
        run: |
          scrapy crawl rest

      - name: Run a script to generate rest2.html
        run: |
          python generate.py < /tmp/scrapy_output.txt > /tmp/rest2.html

      - name: Upload to S3 artifact folder
        uses: medlypharmacy/s3-artifacts-action@master
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.ACCESS_KEY }}
          aws_s3_bucket_name: ${{ secrets.BUCKET_NAME }}
          source_path: ${{ secrets.FILE }}
          destination_path: ${{ secrets.S3_PATH }}

      - name: Commit report
        run: |
          git config --global user.name 'sdesirazu'
          git config --global user.email 'sdesirazu@users.noreply.github.com'
          git commit -am "Automated report"
          git push
