name: Spider

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:


jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run a single-line script
        run: |
          pip install scrapy

      - name: Delete old file scrapy_out.txt
        run: |
          rm -f /tmp/scrapy_out.txt

      - name: Delete old file rest2.html
        run: |
          rm -f rest2.html

      - name: Directory listing
        run: |
          ls /tmp
          ls ~
          pwd
          ls

      - name: Run a scrapy crawl
        run: |
          scrapy crawl rest
          ls /tmp
          ls ~
          ls

      - name: Run a script to generate rest2.html
        run: |
          python generate.py < /tmp/scrapy_out.txt > rest2.html

      - name: Commit report
        run: |
          git config --global user.name 'sdesirazu'
          git config --global user.email 'sdesirazu@users.noreply.github.com'
          git commit -am "Automated report"
          git push
